version: "3"
services:
  backend:
    build: ./backend
    image: "backend"
    container_name: "backend"
    networks:
      - some
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    image: "frontend"
    container_name: "frontend"
    networks:
      - some
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  some:
    driver: bridge
