version: "3"
services:
  backend:
    build: ./backend
    image: backend
    container_name: "backend"
    networks:
      - some
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres

  db:
    image: "postgres"
    container_name: "postgres"
    networks:
      - some
    ports:
      - "5432:5432"
    environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres

networks:
  some:
    driver: bridge
